rust:
  repo: https://github.com/matrix-org/matrix-rust-sdk
  branch: main
  manifestPath: bindings/matrix-sdk-ffi/Cargo.toml
web:
  workspace: true
  manifestPath: rust_modules/matrix-rust-sdk/bindings/wasm/Cargo.toml
  features: ["native-tls", "js", "indexeddb"]
  default_features: false
